pipeline {
    agent any
    tools {
        maven "maven"
        jdk "17"
    }
    environment{
        dockerhub=credentials('docker-hub-credential')
    }
    stages {
        stage('Build maven'){
            steps{
                checkout scmGit(branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/CharlesZhang90/Airlab-backend.git']])
                bat 'mvn -f arilab/pom.xml clean install'
            }
        }
        stage('Build image'){
            steps{
                bat 'docker build -f arilab/Dockerfile -t zhangnaiyuan47/arilab .'
            }
        }
        stage('Push image') {
            steps{
                bat 'echo $dockerhub_PSW | docker login -u $dockerhub_USR --password-stdin'
                bat "docker push zhangnaiyuan47/arilab"
            }
        }
    }
}